import axios from "axios";

export async function generateMetadata({ params }) {
    
  try {
    const response = await axios.get(
      `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/books/${params.BookDetails}`
    );

    const data = response?.data?.data;

    return {
      title: data?.title || "تفاصيل الكتاب",
      description: data?.description || "Generated by create next app",
      keywords: data?.keywords?.join(", ") || "",
    };
  } catch (error) {
    console.error("Error fetching metadata", error);

    return {
      title: "تفاصيل الكتاب",
      description: "Generated by create next app",
      keywords: "",
    };
  }
}

export default function BookLayout({ children }) {
  return <div>{children}</div>;
}
