import { api } from "@/context/ApiText/APITEXT";
import axios from "axios";

export async function generateMetadata({ params }) {
    
  try {
    const response = await axios.get(
      `${api}/api/authors/${params.AuthorAcc}`
    );

    const data = response?.data?.data;

    return {
      title: data?.name || "تفاصيل المؤلف",
      description: data?.biography || "Generated by create next app",
      keywords: data?.keywords?.join(", ") || "",
    };
  } catch (error) {
    console.error("Error fetching metadata", error);

    return {
      title: "تفاصيل المؤلف",
      description: "Generated by create next app",
      keywords: "",
    };
  }
}

export default function AuthorsLayout({ children }) {
  return <div>{children}</div>;
}
