import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import "./globals.css";




export const metadata = {
  title: "مكتبه كتب",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  lang="ar" dir="rtl">

    <head>
    <Head>
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;400;700;900&display=swap" rel="stylesheet" />
    </Head>
    </head>

      <body >
        {children}
      </body>
    </html>
  );
}
