
import "bootstrap/dist/css/bootstrap.min.css"; 
import "./globals.css"; 
import Head from "next/head";
import { AuthProvider } from "@/context/AuthContext";
import ErrorBoundary from "@/Components/ErrorBoundary";


export const metadata = {
  title: "المكتبة الاندلسية",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      
      
        <link
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;400;700;900&display=swap"
          rel="stylesheet"
        />

        <link 
        rel="icon"
        href="Images/logo.svg"
        />



      <body>
        {/* <ErrorBoundary> */}
          <AuthProvider>
            {children}
          </AuthProvider>
        {/* </ErrorBoundary> */}

      </body>
    </html>
  );
}
